# Offense count: 1
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'br_documents.gemspec'

# Offense count: 1
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RubyVersionGlobalsUsage:
  Exclude:
    - 'br_documents.gemspec'

# Offense count: 1
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
   - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never # default: always

# Offense count: 39
# Cop supports --auto-correct.
Style/RedundantRegexpEscape:
  Enabled: false

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'lib/br_documents/cnpj_cpf/cnpj.rb'
    - 'lib/br_documents/cnpj_cpf/document.rb'
    - 'lib/br_documents/ie/ac.rb'
    - 'lib/br_documents/ie/ba.rb'
    - 'lib/br_documents/ie/mg.rb'
    - 'lib/br_documents/ie/mt.rb'
    - 'lib/br_documents/ie/pattern1.rb'
    - 'lib/br_documents/ie/pattern2.rb'
    - 'lib/br_documents/ie/pe.rb'
    - 'lib/br_documents/ie/rn.rb'
    - 'lib/br_documents/ie/ro.rb'
    - 'lib/br_documents/ie/rs.rb'
    - 'lib/br_documents/ie/sp.rb'
    - 'spec/ie/shared_examples_for_to_remove_all_masks.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Exclude:
    - 'br_documents.gemspec'

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
