name: Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - uses: actions/cache@v2
        with:
          path: .
          key: br-documents-cache-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle check || bundle install

      - uses: actions/cache@v2
        with:
          path: ./vendor/bundle
          key: br-documents-cache-v1-{{ $GITHUB_SHA }}
          restore-keys: br-documents-cache-v1-{{ checksum "Gemfile.lock" }}

  rspec:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - uses: actions/cache@v2
        with:
          path: ./vendor/bundle
          key: br-documents-cache-v1-{{ $GITHUB_SHA }}
          restore-keys: br-documents-cache-v1-{{ checksum "Gemfile.lock" }}

      - run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: |
            ./cc-test-reporter before-build
            bundle exec rspec
            ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID --exit-code $?
        env:
           CC_TEST_REPORTER_ID: fcdce38fdc40812bb038186980f11f72939e41be02f372371e535ffd63fed22b
