name: Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: actions/cache@v2
        with:
          path: .
          key: br-documents-cache-v1-{{ checksum "Gemfile.lock" }}
          restore-keys: br-documents-cache-v1-

      - run: bundle check || bundle install

      - uses: actions/cache@v2
        with:
          path: ./vendor/bundle
          key: br-documents-cache-v1-{{ checksum "Gemfile.lock" }}

      - uses: actions/cache@v2
        with:
          path: .
          key: br-documents-cache-v1-{{ checksum "Gemfile.lock" }}
          restore-keys: br-documents-cache-v1-

      - run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: bundle exec rspec
      - run: ./cc-test-reporter after-build --exit-code $?
